apiVersion: v1
kind: Service
metadata:
  name: fullstack-test
  namespace: cloudeefy
  labels:
    app: fullstack-test
    framework: nextjs
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # For AWS
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: fullstack-test
  sessionAffinity: ClientIP  # Sticky sessions for SSR
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours
