apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k8s-deployment.yaml
  - k8s-service.yaml
  - k8s-configmap.yaml
  - k8s-hpa.yaml
  - k8s-virtualservice.yaml
  - k8s-destinationrule.yaml

images:
  - name: rg.fr-par.scw.cloud/cloudeefy/fullstack-test
    newTag: latest
